import sequelize from '../config/db.js';
import User from './User.js';
import Project from './Project.js';
import Team from './Team.js';
import TeamMember from './TeamMember.js';
import Task from './Task.js';
import TaskDependency from './TaskDependency.js';
import Comment from './Comment.js';
import Attachment from './Attachment.js';
import TimeEntry from './TimeEntry.js';
User.hasMany(TeamMember, { foreignKey: 'userId', as: 'teamMemberships' });
TeamMember.belongsTo(User, { foreignKey: 'userId', as: 'user' });
Project.hasMany(Team, { foreignKey: 'projectId', as: 'teams' });
Team.belongsTo(Project, { foreignKey: 'projectId', as: 'project' });
Team.hasMany(TeamMember, { foreignKey: 'teamId', as: 'members' });
TeamMember.belongsTo(Team, { foreignKey: 'teamId' });
Project.hasMany(Task, { foreignKey: 'projectId', as: 'tasks' });
Task.belongsTo(Project, { foreignKey: 'projectId', as: 'project' });
User.hasMany(Task, { foreignKey: 'assigneeId', as: 'assignedTasks' });
Task.belongsTo(User, { foreignKey: 'assigneeId', as: 'assignee' });
Task.hasMany(TaskDependency, { foreignKey: 'taskId', as: 'dependencies' });
TaskDependency.belongsTo(Task, { foreignKey: 'taskId' });
Task.hasMany(Comment, { foreignKey: 'taskId', as: 'comments' });
Comment.belongsTo(Task, { foreignKey: 'taskId' });
User.hasMany(Comment, { foreignKey: 'userId', as: 'comments' });
Comment.belongsTo(User, { foreignKey: 'userId', as: 'author' });
Task.hasMany(Attachment, { foreignKey: 'taskId', as: 'attachments' });
Project.hasMany(Attachment, { foreignKey: 'projectId', as: 'projectAttachments' });
Attachment.belongsTo(User, { foreignKey: 'uploadedBy', as: 'uploader' });
Task.hasMany(TimeEntry, { foreignKey: 'taskId', as: 'timeEntries' });
User.hasMany(TimeEntry, { foreignKey: 'userId', as: 'timeEntries' });
export { sequelize, User, Project, Team, TeamMember, Task, TaskDependency, Comment, Attachment, TimeEntry };
